# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.prod }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.global.prod }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.global.prod }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.prod }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.global.prod }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: pluma-operator
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ template "operator.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
