apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.prod }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.global.prod }}
spec:
  selector:
    app: {{ .Values.global.prod }}
  ports:
    - name: http-metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
