// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	bytes "bytes"

	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for HelmAppSpec
func (this *HelmAppSpec) MarshalJSON() ([]byte, error) {
	str, err := HelmappMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HelmAppSpec
func (this *HelmAppSpec) UnmarshalJSON(b []byte) error {
	return HelmappUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HelmComponent
func (this *HelmComponent) MarshalJSON() ([]byte, error) {
	str, err := HelmappMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HelmComponent
func (this *HelmComponent) UnmarshalJSON(b []byte) error {
	return HelmappUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HelmRepo
func (this *HelmRepo) MarshalJSON() ([]byte, error) {
	str, err := HelmappMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HelmRepo
func (this *HelmRepo) UnmarshalJSON(b []byte) error {
	return HelmappUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HelmAppStatus
func (this *HelmAppStatus) MarshalJSON() ([]byte, error) {
	str, err := HelmappMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HelmAppStatus
func (this *HelmAppStatus) UnmarshalJSON(b []byte) error {
	return HelmappUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HelmComponentStatus
func (this *HelmComponentStatus) MarshalJSON() ([]byte, error) {
	str, err := HelmappMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HelmComponentStatus
func (this *HelmComponentStatus) UnmarshalJSON(b []byte) error {
	return HelmappUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HelmResourceStatus
func (this *HelmResourceStatus) MarshalJSON() ([]byte, error) {
	str, err := HelmappMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HelmResourceStatus
func (this *HelmResourceStatus) UnmarshalJSON(b []byte) error {
	return HelmappUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	HelmappMarshaler   = &jsonpb.Marshaler{}
	HelmappUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
