// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: operator/v1alpha1/helmapp.proto

package v1alpha1

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Phase int32

const (
	Phase_UNKNOWN     Phase = 0
	Phase_RECONCILING Phase = 1
	Phase_SUCCEEDED   Phase = 2
	Phase_FAILED      Phase = 3
	Phase_DELETING    Phase = 4
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "UNKNOWN",
		1: "RECONCILING",
		2: "SUCCEEDED",
		3: "FAILED",
		4: "DELETING",
	}
	Phase_value = map[string]int32{
		"UNKNOWN":     0,
		"RECONCILING": 1,
		"SUCCEEDED":   2,
		"FAILED":      3,
		"DELETING":    4,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_operator_v1alpha1_helmapp_proto_enumTypes[0].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_operator_v1alpha1_helmapp_proto_enumTypes[0]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_operator_v1alpha1_helmapp_proto_rawDescGZIP(), []int{0}
}

type HelmAppSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Components []*HelmComponent `protobuf:"bytes,1,rep,name=components,proto3" json:"components,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	GlobalValues *structpb.Struct `protobuf:"bytes,2,opt,name=globalValues,proto3" json:"globalValues,omitempty"`
	Repo         *HelmRepo        `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
}

func (x *HelmAppSpec) Reset() {
	*x = HelmAppSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_v1alpha1_helmapp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelmAppSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelmAppSpec) ProtoMessage() {}

func (x *HelmAppSpec) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1alpha1_helmapp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelmAppSpec.ProtoReflect.Descriptor instead.
func (*HelmAppSpec) Descriptor() ([]byte, []int) {
	return file_operator_v1alpha1_helmapp_proto_rawDescGZIP(), []int{0}
}

func (x *HelmAppSpec) GetComponents() []*HelmComponent {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *HelmAppSpec) GetGlobalValues() *structpb.Struct {
	if x != nil {
		return x.GlobalValues
	}
	return nil
}

func (x *HelmAppSpec) GetRepo() *HelmRepo {
	if x != nil {
		return x.Repo
	}
	return nil
}

type HelmComponent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Chart   string `protobuf:"bytes,2,opt,name=chart,proto3" json:"chart,omitempty"`
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	ComponentValues *structpb.Struct `protobuf:"bytes,4,opt,name=componentValues,proto3" json:"componentValues,omitempty"`
	Repo            *HelmRepo        `protobuf:"bytes,5,opt,name=repo,proto3" json:"repo,omitempty"`
}

func (x *HelmComponent) Reset() {
	*x = HelmComponent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_v1alpha1_helmapp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelmComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelmComponent) ProtoMessage() {}

func (x *HelmComponent) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1alpha1_helmapp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelmComponent.ProtoReflect.Descriptor instead.
func (*HelmComponent) Descriptor() ([]byte, []int) {
	return file_operator_v1alpha1_helmapp_proto_rawDescGZIP(), []int{1}
}

func (x *HelmComponent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelmComponent) GetChart() string {
	if x != nil {
		return x.Chart
	}
	return ""
}

func (x *HelmComponent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HelmComponent) GetComponentValues() *structpb.Struct {
	if x != nil {
		return x.ComponentValues
	}
	return nil
}

func (x *HelmComponent) GetRepo() *HelmRepo {
	if x != nil {
		return x.Repo
	}
	return nil
}

type HelmRepo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url  string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *HelmRepo) Reset() {
	*x = HelmRepo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_v1alpha1_helmapp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelmRepo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelmRepo) ProtoMessage() {}

func (x *HelmRepo) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1alpha1_helmapp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelmRepo.ProtoReflect.Descriptor instead.
func (*HelmRepo) Descriptor() ([]byte, []int) {
	return file_operator_v1alpha1_helmapp_proto_rawDescGZIP(), []int{2}
}

func (x *HelmRepo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelmRepo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type HelmAppStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// +kubebuilder:validation:Enum=UNKNOWN;RECONCILING;SUCCEEDED;FAILED;DELETING
	// +kubebuilder:validation:Format:type=string
	Phase      Phase                  `protobuf:"varint,1,opt,name=phase,proto3,enum=pluma.operator.v1alpha1.Phase" json:"phase,omitempty"`
	Components []*HelmComponentStatus `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
}

func (x *HelmAppStatus) Reset() {
	*x = HelmAppStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_v1alpha1_helmapp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelmAppStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelmAppStatus) ProtoMessage() {}

func (x *HelmAppStatus) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1alpha1_helmapp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelmAppStatus.ProtoReflect.Descriptor instead.
func (*HelmAppStatus) Descriptor() ([]byte, []int) {
	return file_operator_v1alpha1_helmapp_proto_rawDescGZIP(), []int{3}
}

func (x *HelmAppStatus) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_UNKNOWN
}

func (x *HelmAppStatus) GetComponents() []*HelmComponentStatus {
	if x != nil {
		return x.Components
	}
	return nil
}

type HelmComponentStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status         string                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message        string                `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Version        string                `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Resources      []*HelmResourceStatus `protobuf:"bytes,5,rep,name=resources,proto3" json:"resources,omitempty"`
	ResourcesTotal int32                 `protobuf:"varint,6,opt,name=resourcesTotal,proto3" json:"resourcesTotal,omitempty"`
}

func (x *HelmComponentStatus) Reset() {
	*x = HelmComponentStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_v1alpha1_helmapp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelmComponentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelmComponentStatus) ProtoMessage() {}

func (x *HelmComponentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1alpha1_helmapp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelmComponentStatus.ProtoReflect.Descriptor instead.
func (*HelmComponentStatus) Descriptor() ([]byte, []int) {
	return file_operator_v1alpha1_helmapp_proto_rawDescGZIP(), []int{4}
}

func (x *HelmComponentStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelmComponentStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HelmComponentStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HelmComponentStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HelmComponentStatus) GetResources() []*HelmResourceStatus {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *HelmComponentStatus) GetResourcesTotal() int32 {
	if x != nil {
		return x.ResourcesTotal
	}
	return 0
}

type HelmResourceStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiVersion string `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Kind       string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Namespace  string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *HelmResourceStatus) Reset() {
	*x = HelmResourceStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_v1alpha1_helmapp_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelmResourceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelmResourceStatus) ProtoMessage() {}

func (x *HelmResourceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1alpha1_helmapp_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelmResourceStatus.ProtoReflect.Descriptor instead.
func (*HelmResourceStatus) Descriptor() ([]byte, []int) {
	return file_operator_v1alpha1_helmapp_proto_rawDescGZIP(), []int{5}
}

func (x *HelmResourceStatus) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *HelmResourceStatus) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *HelmResourceStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelmResourceStatus) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

var File_operator_v1alpha1_helmapp_proto protoreflect.FileDescriptor

var file_operator_v1alpha1_helmapp_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2f, 0x68, 0x65, 0x6c, 0x6d, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x17, 0x70, 0x6c, 0x75, 0x6d, 0x61, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc9, 0x01, 0x0a, 0x0b, 0x48, 0x65,
	0x6c, 0x6d, 0x41, 0x70, 0x70, 0x53, 0x70, 0x65, 0x63, 0x12, 0x46, 0x0a, 0x0a, 0x63, 0x6f, 0x6d,
	0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e,
	0x70, 0x6c, 0x75, 0x6d, 0x61, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x48, 0x65, 0x6c, 0x6d, 0x43, 0x6f, 0x6d, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x3b, 0x0a, 0x0c, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x52, 0x0c, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x35,
	0x0a, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70,
	0x6c, 0x75, 0x6d, 0x61, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x48, 0x65, 0x6c, 0x6d, 0x52, 0x65, 0x70, 0x6f, 0x52,
	0x04, 0x72, 0x65, 0x70, 0x6f, 0x22, 0xcd, 0x01, 0x0a, 0x0d, 0x48, 0x65, 0x6c, 0x6d, 0x43, 0x6f,
	0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x68, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x68, 0x61, 0x72,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x41, 0x0a, 0x0f, 0x63,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x0f, 0x63,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x35,
	0x0a, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70,
	0x6c, 0x75, 0x6d, 0x61, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x48, 0x65, 0x6c, 0x6d, 0x52, 0x65, 0x70, 0x6f, 0x52,
	0x04, 0x72, 0x65, 0x70, 0x6f, 0x22, 0x30, 0x0a, 0x08, 0x48, 0x65, 0x6c, 0x6d, 0x52, 0x65, 0x70,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x93, 0x01, 0x0a, 0x0d, 0x48, 0x65, 0x6c, 0x6d,
	0x41, 0x70, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x34, 0x0a, 0x05, 0x70, 0x68, 0x61,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x70, 0x6c, 0x75, 0x6d, 0x61,
	0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2e, 0x50, 0x68, 0x61, 0x73, 0x65, 0x52, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x12,
	0x4c, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70, 0x6c, 0x75, 0x6d, 0x61, 0x2e, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x48, 0x65,
	0x6c, 0x6d, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x22, 0xe8, 0x01,
	0x0a, 0x13, 0x48, 0x65, 0x6c, 0x6d, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x49, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x70, 0x6c, 0x75, 0x6d, 0x61,
	0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2e, 0x48, 0x65, 0x6c, 0x6d, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x7a, 0x0a, 0x12, 0x48, 0x65, 0x6c, 0x6d,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x2a, 0x4e, 0x0a, 0x05, 0x50, 0x68, 0x61, 0x73, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x45,
	0x43, 0x4f, 0x4e, 0x43, 0x49, 0x4c, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x53,
	0x55, 0x43, 0x43, 0x45, 0x45, 0x44, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41,
	0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x49,
	0x4e, 0x47, 0x10, 0x04, 0x42, 0x20, 0x5a, 0x1e, 0x70, 0x6c, 0x75, 0x6d, 0x61, 0x2e, 0x69, 0x6f,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_operator_v1alpha1_helmapp_proto_rawDescOnce sync.Once
	file_operator_v1alpha1_helmapp_proto_rawDescData = file_operator_v1alpha1_helmapp_proto_rawDesc
)

func file_operator_v1alpha1_helmapp_proto_rawDescGZIP() []byte {
	file_operator_v1alpha1_helmapp_proto_rawDescOnce.Do(func() {
		file_operator_v1alpha1_helmapp_proto_rawDescData = protoimpl.X.CompressGZIP(file_operator_v1alpha1_helmapp_proto_rawDescData)
	})
	return file_operator_v1alpha1_helmapp_proto_rawDescData
}

var file_operator_v1alpha1_helmapp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_operator_v1alpha1_helmapp_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_operator_v1alpha1_helmapp_proto_goTypes = []interface{}{
	(Phase)(0),                  // 0: pluma.operator.v1alpha1.Phase
	(*HelmAppSpec)(nil),         // 1: pluma.operator.v1alpha1.HelmAppSpec
	(*HelmComponent)(nil),       // 2: pluma.operator.v1alpha1.HelmComponent
	(*HelmRepo)(nil),            // 3: pluma.operator.v1alpha1.HelmRepo
	(*HelmAppStatus)(nil),       // 4: pluma.operator.v1alpha1.HelmAppStatus
	(*HelmComponentStatus)(nil), // 5: pluma.operator.v1alpha1.HelmComponentStatus
	(*HelmResourceStatus)(nil),  // 6: pluma.operator.v1alpha1.HelmResourceStatus
	(*structpb.Struct)(nil),     // 7: google.protobuf.Struct
}
var file_operator_v1alpha1_helmapp_proto_depIdxs = []int32{
	2, // 0: pluma.operator.v1alpha1.HelmAppSpec.components:type_name -> pluma.operator.v1alpha1.HelmComponent
	7, // 1: pluma.operator.v1alpha1.HelmAppSpec.globalValues:type_name -> google.protobuf.Struct
	3, // 2: pluma.operator.v1alpha1.HelmAppSpec.repo:type_name -> pluma.operator.v1alpha1.HelmRepo
	7, // 3: pluma.operator.v1alpha1.HelmComponent.componentValues:type_name -> google.protobuf.Struct
	3, // 4: pluma.operator.v1alpha1.HelmComponent.repo:type_name -> pluma.operator.v1alpha1.HelmRepo
	0, // 5: pluma.operator.v1alpha1.HelmAppStatus.phase:type_name -> pluma.operator.v1alpha1.Phase
	5, // 6: pluma.operator.v1alpha1.HelmAppStatus.components:type_name -> pluma.operator.v1alpha1.HelmComponentStatus
	6, // 7: pluma.operator.v1alpha1.HelmComponentStatus.resources:type_name -> pluma.operator.v1alpha1.HelmResourceStatus
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_operator_v1alpha1_helmapp_proto_init() }
func file_operator_v1alpha1_helmapp_proto_init() {
	if File_operator_v1alpha1_helmapp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_operator_v1alpha1_helmapp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelmAppSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_v1alpha1_helmapp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelmComponent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_v1alpha1_helmapp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelmRepo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_v1alpha1_helmapp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelmAppStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_v1alpha1_helmapp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelmComponentStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_v1alpha1_helmapp_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelmResourceStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_operator_v1alpha1_helmapp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_operator_v1alpha1_helmapp_proto_goTypes,
		DependencyIndexes: file_operator_v1alpha1_helmapp_proto_depIdxs,
		EnumInfos:         file_operator_v1alpha1_helmapp_proto_enumTypes,
		MessageInfos:      file_operator_v1alpha1_helmapp_proto_msgTypes,
	}.Build()
	File_operator_v1alpha1_helmapp_proto = out.File
	file_operator_v1alpha1_helmapp_proto_rawDesc = nil
	file_operator_v1alpha1_helmapp_proto_goTypes = nil
	file_operator_v1alpha1_helmapp_proto_depIdxs = nil
}
